### ISSUE TITLE
Compile error InitializeDefaultConfiguration

### ISSUE THREAD

**Issue by w1op** [ranorex/Ranorex-Jira-Integration#7]
Hi all,
this is my first time using github so I am not completely sure whether I can directly contribute a solution on a issue or track this as an issue. So I took the second one.

Compiling using the latest Ranorex 9.0.0 there is an error in InitializeDefaultConfiguration line 154 'IsEmpty' is not valid.

The solution is

if (this.EnableJiraIntegration == "default" || String.IsNullOrEmpty(this.EnableJiraIntegration))

**Comment by ahoisl** [comment]
Thank you for reporting this issue. It's fixed the build with the latest 0.1.2 version, also pushed to nuget already.
See commit https://github.com/ranorex/Ranorex-Jira-Integration/commit/548f7fb4bc6fa425dbb2a584321938cbf04c0a35
